# Generated by Django 4.1.5 on 2023-01-28 20:30

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='без группы', max_length=100, verbose_name='группа товара')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField(default=0, verbose_name='прибыль')),
                ('date', models.CharField(default='profit', max_length=30, verbose_name='месяц отчетности')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=10000, verbose_name='товар')),
                ('article', models.CharField(default=' ', max_length=100, verbose_name='артикул')),
                ('create_at', models.CharField(default=datetime.date(2023, 1, 28), max_length=30, verbose_name='дата добавления')),
                ('comment', models.CharField(default=' ', max_length=100, verbose_name='описание')),
                ('price_zakupka', models.IntegerField(verbose_name='цена закупочная')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('spd_count', models.IntegerField(default=0, verbose_name='колличество СПБ')),
                ('mos_count', models.IntegerField(default=0, verbose_name='колличество МОСКВА')),
                ('file', models.FileField(blank=True, default='files/no_products.jpg', null=True, upload_to='files/', verbose_name='фото товара')),
                ('group_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.categorymodel', verbose_name='категория товара')),
            ],
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['products'], name='warehouse_a_product_9b8e5b_gin'),
        ),
    ]
