# Generated by Django 4.1.5 on 2023-01-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='-------', max_length=50, null=True, verbose_name='имя пользователя')),
                ('city', models.CharField(blank=True, default='-------', max_length=30, verbose_name='город')),
                ('surname', models.CharField(blank=True, default='-------', max_length=30, verbose_name='фамилия')),
                ('phone', models.CharField(blank=True, default='-------', max_length=30, verbose_name='номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000, verbose_name='текст')),
                ('text_100', models.CharField(max_length=100, verbose_name='текст_100_символов')),
                ('create_at', models.CharField(max_length=100)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_base.authorprofile', verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_base.blogrecord')),
            ],
        ),
    ]
