# Generated by Django 4.1.5 on 2023-01-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='без группы', max_length=100, verbose_name='группа товара')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=10000, verbose_name='товар')),
                ('article', models.CharField(default='без артикула', max_length=100, verbose_name='артикул')),
                ('create_at', models.CharField(max_length=100, verbose_name='дата добавления')),
                ('comment', models.CharField(default='без артикула', max_length=100, verbose_name='описание')),
                ('file', models.FileField(upload_to='files/')),
                ('group_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_base.categorymodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogrecord',
            name='username',
        ),
        migrations.RemoveField(
            model_name='files',
            name='post',
        ),
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
        migrations.DeleteModel(
            name='BlogRecord',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
