# Generated by Django 4.1.5 on 2023-01-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0002_categorymodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='mos_count',
            field=models.IntegerField(default=0, verbose_name='колличество МОСКВА'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price_zakupka',
            field=models.IntegerField(default=0, verbose_name='цена закупочная'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='spd_count',
            field=models.IntegerField(default=0, verbose_name='колличество СПБ'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
