# Generated by Django 4.1.5 on 2023-01-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0003_productmodel_mos_count_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='article',
            field=models.CharField(default=' ', max_length=100, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='comment',
            field=models.CharField(default=' ', max_length=100, verbose_name='описание'),
        ),
    ]
