# Generated by Django 4.1.1 on 2023-01-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0004_alter_productmodel_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField(verbose_name='прибыль')),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='group_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_base.categorymodel', verbose_name='категория товара'),
        ),
    ]
