# Generated by Django 4.1.1 on 2023-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0005_profit_alter_productmodel_group_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='прибыль'),
        ),
    ]
