# Generated by Django 4.1.5 on 2023-01-17 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0006_alter_profit_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='create_at',
            field=models.CharField(default=datetime.date(2023, 1, 17), max_length=30, verbose_name='дата добавления'),
        ),
    ]
