# Generated by Django 4.1.5 on 2023-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0008_productmodel_my_base_pro_product_3948c7_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='file',
            field=models.FileField(blank=True, default='media/files/000005390006.png', null=True, upload_to='files/', verbose_name='фото товара'),
        ),
    ]
