# Generated by Django 4.1.5 on 2023-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0009_alter_productmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='file',
            field=models.FileField(blank=True, default='files/no_products.jpg', null=True, upload_to='files/', verbose_name='фото товара'),
        ),
    ]
