# Generated by Django 4.1.5 on 2023-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0010_alter_productmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='date',
            field=models.CharField(default='profit', max_length=30, verbose_name='месяц отчетности'),
        ),
    ]
