# Generated by Django 4.1.5 on 2023-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_base', '0012_alter_productmodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price_zakupka',
            field=models.IntegerField(verbose_name='цена закупочная'),
        ),
    ]
